{"name": "GET request example", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x046EA7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\step_def_CRUD.py\", line 76, in step_impl\n    data=http_request_body)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "steps": [{"name": "Given Set basic web application url is \"http://localhost:8080/imademethink/restfulapi/account_basic/\"", "status": "passed", "start": 1540490925119, "stop": 1540490925119}, {"name": "And Set basic user details as \"<particular>\" and \"<value>\" below", "status": "passed", "attachments": [{"name": ".table", "source": "2712e238-1605-4325-97ee-631ad82db1da-attachment.csv", "type": "text/csv"}], "start": 1540490925134, "stop": 1540490925150}, {"name": "Given Set GET api endpoint as \"signup\"", "status": "passed", "start": 1540490925150, "stop": 1540490925150}, {"name": "When Set HEADER param request content type as \"application/json\"", "status": "passed", "start": 1540490925150, "stop": 1540490925150}, {"name": "And Set HEADER param response accept type as \"application/json\"", "status": "passed", "start": 1540490925150, "stop": 1540490925150}, {"name": "And Set Query param as \"empty\"", "status": "passed", "start": 1540490925150, "stop": 1540490925150}, {"name": "And Raise \"GET\" HTTP request", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x046EA7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\step_def_CRUD.py\", line 76, in step_impl\n    data=http_request_body)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1540490925150, "stop": 1540490927684}, {"name": "Then Valid HTTP response should be received", "status": "skipped", "start": 1540490927700, "stop": 1540490927700}, {"name": "And Response http code should be 200", "status": "skipped", "start": 1540490927700, "stop": 1540490927700}, {"name": "And Response HEADER content type should be \"application/json\"", "status": "skipped", "start": 1540490927700, "stop": 1540490927700}, {"name": "And Response BODY should not be null or empty", "status": "skipped", "start": 1540490927700, "stop": 1540490927700}, {"name": "And Response BODY parsing for \"GET__signup\" should be successful", "status": "skipped", "start": 1540490927700, "stop": 1540490927700}], "start": 1540490925119, "stop": 1540490927700, "uuid": "2dfb5082-4357-4c44-9340-c59eb879f996", "historyId": "7100a2c4f19733491cca4ed48252e4e9", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "REST API testing framework using Java REST Assured or JayWay Libraries"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}