{"name": "POST request example", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0475F530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\step_def_CRUD.py\", line 83, in step_impl\n    data=http_request_body)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 116, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "steps": [{"name": "Given Set basic web application url is \"http://localhost:8080/imademethink/restfulapi/account_basic/\"", "status": "passed", "start": 1540490927716, "stop": 1540490927716}, {"name": "And Set basic user details as \"<particular>\" and \"<value>\" below", "status": "passed", "attachments": [{"name": ".table", "source": "e11d7a65-2537-4e7f-a560-808aa8d47ca3-attachment.csv", "type": "text/csv"}], "start": 1540490927716, "stop": 1540490927731}, {"name": "Given Set POST api endpoint as \"signup\"", "status": "passed", "start": 1540490927731, "stop": 1540490927731}, {"name": "When Set HEADER param request content type as \"application/x-www-form-urlencoded\"", "status": "passed", "start": 1540490927731, "stop": 1540490927747}, {"name": "And Set HEADER param response accept type as \"application/json\"", "status": "passed", "start": 1540490927747, "stop": 1540490927747}, {"name": "And Set BODY form param using basic user details", "status": "passed", "start": 1540490927747, "stop": 1540490927747}, {"name": "And Raise \"POST\" HTTP request", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0475F530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\step_def_CRUD.py\", line 83, in step_impl\n    data=http_request_body)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 116, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\punjr\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1540490927747, "stop": 1540490929798}, {"name": "Then Valid HTTP response should be received", "status": "skipped", "start": 1540490929813, "stop": 1540490929813}, {"name": "And Response http code should be 201", "status": "skipped", "start": 1540490929813, "stop": 1540490929813}, {"name": "And Response HEADER content type should be \"application/json\"", "status": "skipped", "start": 1540490929813, "stop": 1540490929813}, {"name": "And Response BODY should not be null or empty", "status": "skipped", "start": 1540490929813, "stop": 1540490929813}, {"name": "And Response BODY parsing for \"POST__signup\" should be successful", "status": "skipped", "start": 1540490929813, "stop": 1540490929813}], "start": 1540490927716, "stop": 1540490929813, "uuid": "dd088678-a8fc-4221-868d-8ee3214966e5", "historyId": "0bc8078129fb29a3fa6d9465eca516d4", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "REST API testing framework using Java REST Assured or JayWay Libraries"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}